{[
    {"name": "Ibiza Radio", "url": "https://listenssl.ibizaglobalradio.com:8024/stream"},
    {"name": "Deep House", "url": "https://pub0101.101.ru:8000/stream/trust/mp3/128/173"},
    {"name": "Дискотека ссср", "url": "https://pub0101.101.ru:8000/stream/pro/aac/64/144"},
    {"name": "Новая Волна", "url": "http://volgograd.sv-veter.ru:8008/nv_online"},
    {"name": "Русский Рок - Русское Радио", "url": "https://rr-russkijrok.hostingradio.ru/russkijrok96.aacp"},
    {"name": "Русское Радио 96", "url": "https://rusradio.hostingradio.ru/rusradio96.aacp"},
    {"name": "Радио Свобода", "url": "http://n09.radiojar.com/hcrb063nn3quv"},
    {"name": "Русское радио", "url": "https://rusradio.hostingradio.ru/rusradio128.mp3"},
    {"name": "Другая Астрахань 32", "url": "http://89.179.72.53:8070/mini"},
    {"name": "Другая Астрахань", "url": "http://89.179.72.53:8070/live"},
    {"name": "Радио Шансон", "url": "http://chanson.hostingradio.ru:8041/chanson128.mp3"},
    {"name": "Эхо Москвы", "url": "http://ice912.echo.msk.ru:9120/stream"},
    {"name": "Ди Фм", "url": "https://dfm.hostingradio.ru/dfm96.aacp"},
    {"name": "Юмор Фм", "url": "https://pub0301.101.ru:8443/stream/air/mp3/256/102"},
    {"name": "Дискотека 90-х", "url": "http://air.radiorecord.ru:8102/sd90_320"},
    {"name": "Вести Фм", "url": "http://icecast.vgtrk.cdnvideo.ru/vestifm_mp3_192kbps"},
    {"name": "Радио Маяк", "url": "http://icecast.vgtrk.cdnvideo.ru/mayakfm_mp3_192kbps"},
    {"name": "Комсомольская правда", "url": "https://kpradio.hostingradio.ru:8000/russia.radiokp128.mp3"},
    {"name": "Серебряный Дождь 48", "url": "http://213.59.4.27:8000/stream48.mp3"},
    {"name": "Серебряный Дождь", "url": "http://213.59.4.27:8000/silver128.mp3"},
    {"name": "Радио России", "url": "http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_192kbps"},
    {"name": "Радио Рекорд", "url": "http://air.radiorecord.ru:805/rr_320"},
    {"name": "Новое Радио", "url": "http://icecast.newradio.cdnvideo.ru/newradio3"},
    {"name": "Радио Маруся", "url": "http://radio-holding.ru:9000/marusya_default"}
]}
